name: pos_printer_manager
description: flutter package for print or list down both wireless and bluetooth esc printer devices.
version: 3.0.0
homepage: https://github.com/sergiotucano/pos_printer_manager_plus
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  esc_pos_utils_plus:  ^2.0.1+6
  flutter_usb_printer: ^0.1.0+1
  easy_logger: ^0.0.2
  win32: ^5.14.0
  printing: ^5.10.4
  ffi: ^2.1.4
  blue_thermal_printer:
    git:
      url: https://github.com/hazbu/blue_thermal_printer.git
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
