name: pos_printer_manager
description: flutter package for print or list down both wireless and bluetooth esc printer devices.
version: 0.0.6
homepage: https://github.com/sergiotucano/pos_printer_manager_plus

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  esc_pos_utils_plus:  ^2.0.1+6
  flutter_usb_printer:  ^0.1.0+1
  blue_thermal_printer: ^1.2.3
  network_info_plus: ^2.1.4+1
  easy_logger: ^0.0.2
  win32: ^4.1.4
  printing: ^5.10.4
  ffi: ^2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
